services:
  products-service:
    build: ./products-service
    container_name: products-service
    ports:
      - "8001:8000"
    volumes:
      - ./products-service:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - bff-network

  bff-web:
    build: ./bff-web
    container_name: bff-web
    ports:
      - "8000:8000"
    volumes:
      - ./bff-web:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PRODUCTS_SERVICE_URL=http://products-service:8000
    depends_on:
      - products-service
    networks:
      - bff-network

  bff-mobile:
    build: ./bff-mobile
    container_name: bff-mobile
    ports:
      - "8002:8000"
    volumes:
      - ./bff-mobile:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PRODUCTS_SERVICE_URL=http://products-service:8000
    depends_on:
      - products-service
    networks:
      - bff-network

  web-frontend:
    build: ./web-frontend
    container_name: web-frontend
    ports:
      - "3000:80"
    depends_on:
      - bff-web
    networks:
      - bff-network
    environment:
      - VITE_API_URL=http://localhost:8000

networks:
  bff-network:
    driver: bridge